[package]
name = "janus-protocol-rdp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.101"
tokio = { version = "1.49.0", features = ["process", "fs", "time", "rt", "macros"] }
uuid = { version = "1.21.0", features = ["v4"] }
